### ISSUE TITLE
Test runner stuck if Before/After hooks is being used

### ISSUE THREAD

**Issue by janyangyuan** [Balrog994/cucumber-test-runner#10]
In the latest version v0.5.0, it seems like the test run will stuck if we use Before/After hooks

![image](https://github.com/Balrog994/cucumber-test-runner/assets/45619112/2ee49f45-15f7-4d0f-81a6-d1dbb1c066eb)

I saw the following error in debug console when the test run stuck:
```
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at Console.value (node:internal/console/constructor:300:16)
    at Console.warn (node:internal/console/constructor:382:26)
    at ConsoleLogger.error (c:\Workspace\PlaygroundCucumber\node_modules\@cucumber\cucumber\src\api\console_logger.ts:16:18)
    at Socket.<anonymous> (c:\Workspace\PlaygroundCucumber\node_modules\@cucumber\cucumber\src\api\formatters.ts:42:14)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}
```

You can find my repo for the example: https://github.com/janyangyuan/playground-cucumber
It works fine if I comment the Before/After functions and move all the codes to Given/When/Then, so I guess the Before/After hooks break the test-runner.

**Comment by Balrog994** [comment]
Thanks for the report, I'll check it as soon as possible :)
